### ISSUE TITLE
can't start experiments with main.py

### ISSUE THREAD

**Issue by tokarev-i-v** [ZJLAB-AMMI/LLM4RL#1]
Hello! There is no files 'monster.py' and 'Game_multi_heads.py' in 'env' directory
```
from .monster import *
ModuleNotFoundError: No module named 'env.monster'
```

**Comment by lake1115** [comment]
> Hello! There is no files 'monster.py' and 'Game_multi_heads.py' in 'env' directory
> 
> ```
> from .monster import *
> ModuleNotFoundError: No module named 'env.monster'
> ```

This bug has been fixed
