### ISSUE TITLE
Pre-trained LLM model

### ISSUE THREAD

**Issue by fracarfer5** [ZJLAB-AMMI/LLM4RL#4]
Is the "vicuna-7b-x" model from planner.py a pre-trained, fine-tuned model? When it is replaced with a generic "vicuna-7b-v1.5" model, its outputs always return an illegal plan, making the code unreproducible.

**Comment by puz93** [comment]
Vicuna is created by fine-tuning a Llama base model. At the time of our release, the model was based on llama1. The current vicuna model is based on llama2. Therefore, the prompt may no longer be applicable to the current version. The model we used is "vicuna-7b-v1.1". You can find it through: "https://huggingface.co/lmsys/vicuna-7b-v1.1"
